### ISSUE TITLE
ans: Avian Name System Todo List

### ISSUE THREAD

**Issue by alamshafil** [AvianNetwork/Avian#163]
Avian Name System (ANS) Todo List

Read about ANS here: https://github.com/AvianNetwork/aips/blob/main/aip-0004.mediawiki

- [x] Updated asset database for ANS support #162 
- [x] Updated RPC method to show ANS info #162 
- [x] New RPC methods for ANS IDs #162 
- [x] UI changes for creating and reissuing assets with ANS data attached. #162 
- [x] Flightplans (AFP) support #162 
- [x] Basic support for reissuing #162 
- [x] Timestamp-based activation #162 
- [x] Update `createrawtransaction` to support ANS #162
- [x] Asset name checking #162 
- [ ] Fix reissue ANS assets (serialization)
- [ ] Support for subassets/unique assets 
- [ ] In-wallet support for ANS addr
- [ ] New serialization to decrease space used.
- [ ] Add test suite (including benchmarks)
