### ISSUE TITLE
AVN 4.0 Tracker

### ISSUE THREAD

**Issue by alamshafil** [AvianNetwork/Avian#51]
- [x] Fork Bitcoin v22.0
- [x] Add basic Avian rebranding
- [x] Add Avian icons
- [x] Add Avian chainparams.cpp + pow.cpp
- [x] Add dual algo (Crow minix+x16rt)
- [x] Port functions and calls in Bitcoin `key-io.cpp` to `base58.cpp` (CRavenAddress/Secret)
- [x] Add RVN assets
- [x] Fix support with Bitcoin new wallet system
- [x] Test if blockchain is readable and able to connect to peers
- [x] Add new UI

**Comment by alamshafil** [comment]
Close in favor of using Projects tab.
